//! # zkreceipt-verifier
//!
//! Solana Anchor program for the zkReceipt verifier. Consumes Groth16
//! proofs of source-chain finality (generated by `zkreceipt-prover`) and
//! persists the resulting `(slot, state_root)` to a PDA. Downstream programs
//! (e.g. `mppsol_cpi`) read the PDA + verify MPT inclusion proofs to authorize
//! Solana-side settlement of the source-chain payment.
//!
//! ## Status
//!
//! **Partial implementation.** Account-state binding, slot monotonicity, and
//! validator-set-hash matching are enforced, and the **Groth16 proof is really
//! verified** — [`verify_sp1_groth16`] calls `sp1-solana`'s `verify_proof` over
//! the committed public output via Solana's BN254 (`alt_bn128`) syscalls,
//! before any state mutation.
//!
//! The embedded [`ZKRECEIPT_VKEY_HASH`] is a **placeholder** until the guest's
//! real verification key exists (its `verify_update` leaf is incomplete), so
//! the deployed default **rejects every proof** — fail-closed. Remaining:
//!
//! 1. Build the guest → extract the real vkey → replace the placeholder.
//! 2. SP1 version: `sp1-solana` embeds the v5.0.0 vk; the guest must match.
//!
//! See `../../../spec/verifier.md`.

use anchor_lang::prelude::*;
use zkreceipt_light_client::{decode_public_output, PUBLIC_OUTPUT_LEN};

declare_id!("EMDfWFhRSZT749WBBARG3K5h1PQUUCCQcgoYtUg658Yv");
// Placeholder devnet keypair generated at scaffold time. Regenerate via
// `solana-keygen new -o target/deploy/zkreceipt_verifier-keypair.json` and
// `anchor keys sync` once the real deployment keypair is committed (or
// kept in a secrets manager — never in git).

/// SP1 verification-key hash for the zkReceipt finality guest, as printed by
/// `cargo prove vkey` on `prover/program`.
///
/// **PLACEHOLDER.** The guest's `verify_update` leaf is not yet complete (BFT
/// aggregate quorum signature pending — see `spec/light-client.md`), so no real
/// vkey exists yet. Until this is replaced with the real hash,
/// [`update_light_client`] verifies against a non-existent key and therefore
/// **rejects every proof** — the correct fail-closed default for a trustless
/// verifier. The verification machinery itself is real and exercised by the
/// tests against SP1's own proof fixture.
const ZKRECEIPT_VKEY_HASH: &str =
    "0x0000000000000000000000000000000000000000000000000000000000000000";

/// Verify an SP1 Groth16 `proof` over the committed `public_output` bytes
/// against `vkey_hash`, using Solana's BN254 (`alt_bn128`) syscalls (~200K CU).
///
/// Isolated from the instruction so it can be unit-tested directly. Returns
/// [`ZkReceiptError::InvalidProof`] on any failure — the verifier is
/// fail-closed: malformed input, wrong vkey, or an invalid proof all reject.
fn verify_sp1_groth16(proof: &[u8], public_output: &[u8], vkey_hash: &str) -> Result<()> {
    sp1_solana::verify_proof(
        proof,
        public_output,
        vkey_hash,
        sp1_solana::GROTH16_VK_5_0_0_BYTES,
    )
    .map_err(|_| error!(ZkReceiptError::InvalidProof))
}

#[program]
pub mod zkreceipt_verifier {
    use super::*;

    /// One-shot initialization. Creates the [`LightClientState`] PDA and
    /// seeds it with the genesis validator-set hash and starting
    /// finalized root.
    ///
    /// Authority: permissioned to the bootstrap caller (one-time — the
    /// PDA's `init` constraint prevents re-bootstrap).
    pub fn bootstrap(
        ctx: Context<Bootstrap>,
        genesis_validator_set_hash: [u8; 32],
        genesis_slot: u64,
        genesis_state_root: [u8; 32],
    ) -> Result<()> {
        let state = &mut ctx.accounts.light_client_state;
        state.latest_slot = genesis_slot;
        state.state_root = genesis_state_root;
        state.validator_set_hash = genesis_validator_set_hash;
        state.last_update_unix_ts = Clock::get()?.unix_timestamp;
        state.bump = ctx.bumps.light_client_state;
        Ok(())
    }

    /// Verify a Groth16 proof + 112-byte committed public output, advance
    /// the finalized state if valid.
    ///
    /// Authority: permissionless — the proof is the authority. Anyone can
    /// pay the fee and submit; the program accepts iff:
    ///
    /// 1. Public output decodes (length = `PUBLIC_OUTPUT_LEN`).
    /// 2. `outputs.prev_root` matches the currently stored finalized state
    ///    (binds the proof to a specific transition, prevents replay).
    /// 3. `outputs.validator_set_hash` matches the active set in storage.
    /// 4. `outputs.new_root.slot > state.latest_slot` (strict advance).
    /// 5. **TODO:** Groth16 proof bytes verify against the embedded SP1
    ///    verification key. See module docs for the dependency chain.
    pub fn update_light_client(
        ctx: Context<UpdateLightClient>,
        proof: Vec<u8>,
        public_output: [u8; PUBLIC_OUTPUT_LEN],
    ) -> Result<()> {
        let state = &mut ctx.accounts.light_client_state;

        // (0) Cryptographic authentication. The Groth16 proof must verify
        // against the zkReceipt guest's SP1 verification key over exactly the
        // committed `public_output` bytes, using Solana's BN254 (alt_bn128)
        // syscalls (~200K CU). This is what makes the update trustless: no
        // valid proof, no state advance. Runs first so no state is touched on
        // an unauthenticated call.
        verify_sp1_groth16(&proof, &public_output, ZKRECEIPT_VKEY_HASH)?;

        // (1) Decode the proof's committed public outputs.
        let outputs = decode_public_output(&public_output)
            .map_err(|_| error!(ZkReceiptError::InvalidPublicOutput))?;

        // (2) Bind: proof must transition FROM the current finalized state.
        require!(
            outputs.prev_root.slot == state.latest_slot
                && outputs.prev_root.state_root == state.state_root,
            ZkReceiptError::StateBindingMismatch
        );

        // (3) Validator-set hash binding.
        require!(
            outputs.validator_set_hash == state.validator_set_hash,
            ZkReceiptError::StaleValidatorSet
        );

        // (4) Strict slot advance.
        require!(
            outputs.new_root.slot > state.latest_slot,
            ZkReceiptError::NonMonotonicSlot
        );

        // (5) Commit.
        state.latest_slot = outputs.new_root.slot;
        state.state_root = outputs.new_root.state_root;
        state.last_update_unix_ts = Clock::get()?.unix_timestamp;
        Ok(())
    }
}

/// Persistent light-client state PDA.
///
/// Seeds: `[b"light_client_state"]`. One per zkReceipt verifier deployment.
#[account]
pub struct LightClientState {
    /// Most recently finalized Tempo slot.
    pub latest_slot: u64,
    /// State root finalized at `latest_slot`.
    pub state_root: [u8; 32],
    /// Hash commitment of the active validator set.
    pub validator_set_hash: [u8; 32],
    /// Solana `Clock::unix_timestamp` at the last update. Used by
    /// downstream consumers to detect stale roots.
    pub last_update_unix_ts: i64,
    /// PDA bump seed.
    pub bump: u8,
}

impl LightClientState {
    pub const SEED: &'static [u8] = b"light_client_state";
    /// Size in bytes, **excluding** the 8-byte Anchor discriminator.
    /// u64 (8) + [u8;32] (32) + [u8;32] (32) + i64 (8) + u8 (1) = 81.
    pub const SIZE: usize = 8 + 32 + 32 + 8 + 1;
}

#[derive(Accounts)]
pub struct Bootstrap<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + LightClientState::SIZE,
        seeds = [LightClientState::SEED],
        bump,
    )]
    pub light_client_state: Account<'info, LightClientState>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateLightClient<'info> {
    #[account(
        mut,
        seeds = [LightClientState::SEED],
        bump = light_client_state.bump,
    )]
    pub light_client_state: Account<'info, LightClientState>,
    /// The fee-payer for the update transaction. Not an authority — the
    /// proof is the authority.
    pub submitter: Signer<'info>,
}

#[error_code]
pub enum ZkReceiptError {
    #[msg("Groth16 proof verification failed")]
    InvalidProof,
    #[msg("Committed public output bytes failed to decode")]
    InvalidPublicOutput,
    #[msg("Proof's prev_root does not match the current finalized state")]
    StateBindingMismatch,
    #[msg("Validator set hash in proof does not match the active set")]
    StaleValidatorSet,
    #[msg("New slot must be strictly greater than the latest finalized slot")]
    NonMonotonicSlot,
}

#[cfg(test)]
mod tests {
    use super::*;

    // A well-formed-length but invalid proof must be REJECTED — never accepted,
    // never a panic. Exercises the real sp1-solana Groth16 path natively
    // (solana-bn254's host implementation of the BN254 ops), proving the
    // verification machinery runs and fail-closes. The positive path (a valid
    // proof → Ok) needs zkReceipt's own guest proof and lands in Stage 2.
    #[test]
    fn rejects_invalid_proof() {
        let proof = vec![0u8; 260];
        let public_output = [0u8; PUBLIC_OUTPUT_LEN];
        let fib_hash = "0x00bb9e57314d7ee4f65a4b9fb46fbeae0495f2015c5a8a737333680ce6bb424e";
        assert!(verify_sp1_groth16(&proof, &public_output, fib_hash).is_err());
    }

    // The placeholder guest vkey hash must reject everything until the real
    // guest vkey is embedded — the deployed default is fail-closed.
    #[test]
    fn placeholder_vkey_is_fail_closed() {
        let proof = vec![0u8; 260];
        let public_output = [0u8; PUBLIC_OUTPUT_LEN];
        assert!(verify_sp1_groth16(&proof, &public_output, ZKRECEIPT_VKEY_HASH).is_err());
    }
}
