//! # zktempo-verifier
//!
//! Solana Anchor program for the zkTempo.sol verifier. Consumes Groth16
//! proofs of Tempo finality (generated by `zktempo-prover`) and persists
//! the resulting `(slot, state_root)` to a PDA. Downstream programs (e.g.
//! `mppsol_cpi`) read the PDA + verify MPT inclusion proofs to authorize
//! Solana-side settlement of Tempo-originated payments.
//!
//! ## Status
//!
//! **Partial implementation.** Account-state binding, slot monotonicity,
//! and validator-set-hash matching are enforced. The Groth16 proof
//! verification itself is `TODO` pending:
//!
//! 1. SP1 verification key generation (depends on `../../../prover/program/`).
//! 2. `sol_alt_bn128_pairing` syscall wiring (e.g. via `groth16-solana`).
//!
//! Until these land, the program accepts any `proof: Vec<u8>` argument
//! but **still enforces all non-cryptographic consistency checks** —
//! sufficient for downstream integration testing (mppsol_cpi can call
//! through) but NOT for production security.
//!
//! See `../../../spec/verifier.md`.

use anchor_lang::prelude::*;
use zktempo_light_client::{decode_public_output, PUBLIC_OUTPUT_LEN};

declare_id!("EMDfWFhRSZT749WBBARG3K5h1PQUUCCQcgoYtUg658Yv");
// Placeholder devnet keypair generated at scaffold time. Regenerate via
// `solana-keygen new -o target/deploy/zktempo_verifier-keypair.json` and
// `anchor keys sync` once the real deployment keypair is committed (or
// kept in a secrets manager — never in git).

#[program]
pub mod zktempo_verifier {
    use super::*;

    /// One-shot initialization. Creates the [`LightClientState`] PDA and
    /// seeds it with the genesis validator-set hash and starting
    /// finalized root.
    ///
    /// Authority: permissioned to the bootstrap caller (one-time — the
    /// PDA's `init` constraint prevents re-bootstrap).
    pub fn bootstrap(
        ctx: Context<Bootstrap>,
        genesis_validator_set_hash: [u8; 32],
        genesis_slot: u64,
        genesis_state_root: [u8; 32],
    ) -> Result<()> {
        let state = &mut ctx.accounts.light_client_state;
        state.latest_slot = genesis_slot;
        state.state_root = genesis_state_root;
        state.validator_set_hash = genesis_validator_set_hash;
        state.last_update_unix_ts = Clock::get()?.unix_timestamp;
        state.bump = ctx.bumps.light_client_state;
        Ok(())
    }

    /// Verify a Groth16 proof + 112-byte committed public output, advance
    /// the finalized state if valid.
    ///
    /// Authority: permissionless — the proof is the authority. Anyone can
    /// pay the fee and submit; the program accepts iff:
    ///
    /// 1. Public output decodes (length = `PUBLIC_OUTPUT_LEN`).
    /// 2. `outputs.prev_root` matches the currently stored finalized state
    ///    (binds the proof to a specific transition, prevents replay).
    /// 3. `outputs.validator_set_hash` matches the active set in storage.
    /// 4. `outputs.new_root.slot > state.latest_slot` (strict advance).
    /// 5. **TODO:** Groth16 proof bytes verify against the embedded SP1
    ///    verification key. See module docs for the dependency chain.
    pub fn update_light_client(
        ctx: Context<UpdateLightClient>,
        proof: Vec<u8>,
        public_output: [u8; PUBLIC_OUTPUT_LEN],
    ) -> Result<()> {
        let state = &mut ctx.accounts.light_client_state;

        // TODO: verify `proof` bytes against the embedded SP1 verification
        // key using `sol_alt_bn128_pairing`. Without this, the program is
        // structurally complete but cryptographically unauthenticated.
        let _ = proof;

        // (1) Decode the proof's committed public outputs.
        let outputs = decode_public_output(&public_output)
            .map_err(|_| error!(ZkTempoError::InvalidPublicOutput))?;

        // (2) Bind: proof must transition FROM the current finalized state.
        require!(
            outputs.prev_root.slot == state.latest_slot
                && outputs.prev_root.state_root == state.state_root,
            ZkTempoError::StateBindingMismatch
        );

        // (3) Validator-set hash binding.
        require!(
            outputs.validator_set_hash == state.validator_set_hash,
            ZkTempoError::StaleValidatorSet
        );

        // (4) Strict slot advance.
        require!(
            outputs.new_root.slot > state.latest_slot,
            ZkTempoError::NonMonotonicSlot
        );

        // (5) Commit.
        state.latest_slot = outputs.new_root.slot;
        state.state_root = outputs.new_root.state_root;
        state.last_update_unix_ts = Clock::get()?.unix_timestamp;
        Ok(())
    }
}

/// Persistent light-client state PDA.
///
/// Seeds: `[b"light_client_state"]`. One per zkTempo verifier deployment.
#[account]
pub struct LightClientState {
    /// Most recently finalized Tempo slot.
    pub latest_slot: u64,
    /// State root finalized at `latest_slot`.
    pub state_root: [u8; 32],
    /// Hash commitment of the active validator set.
    pub validator_set_hash: [u8; 32],
    /// Solana `Clock::unix_timestamp` at the last update. Used by
    /// downstream consumers to detect stale roots.
    pub last_update_unix_ts: i64,
    /// PDA bump seed.
    pub bump: u8,
}

impl LightClientState {
    pub const SEED: &'static [u8] = b"light_client_state";
    /// Size in bytes, **excluding** the 8-byte Anchor discriminator.
    /// u64 (8) + [u8;32] (32) + [u8;32] (32) + i64 (8) + u8 (1) = 81.
    pub const SIZE: usize = 8 + 32 + 32 + 8 + 1;
}

#[derive(Accounts)]
pub struct Bootstrap<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + LightClientState::SIZE,
        seeds = [LightClientState::SEED],
        bump,
    )]
    pub light_client_state: Account<'info, LightClientState>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateLightClient<'info> {
    #[account(
        mut,
        seeds = [LightClientState::SEED],
        bump = light_client_state.bump,
    )]
    pub light_client_state: Account<'info, LightClientState>,
    /// The fee-payer for the update transaction. Not an authority — the
    /// proof is the authority.
    pub submitter: Signer<'info>,
}

#[error_code]
pub enum ZkTempoError {
    #[msg("Groth16 proof verification failed")]
    InvalidProof,
    #[msg("Committed public output bytes failed to decode")]
    InvalidPublicOutput,
    #[msg("Proof's prev_root does not match the current finalized state")]
    StateBindingMismatch,
    #[msg("Validator set hash in proof does not match the active set")]
    StaleValidatorSet,
    #[msg("New slot must be strictly greater than the latest finalized slot")]
    NonMonotonicSlot,
}
