//! # zktempo-verifier
//!
//! Solana Anchor program for the zkTempo.sol verifier. Consumes Groth16
//! proofs of Tempo finality (generated by `zktempo-prover`) and persists
//! the resulting `(slot, state_root)` to a PDA. Downstream programs (e.g.
//! `mppsol_cpi`) read the PDA + verify MPT inclusion proofs to authorize
//! Solana-side settlement of Tempo-originated payments.
//!
//! ## Status
//!
//! Scaffold. Account layouts and instruction interfaces are pinned;
//! instruction bodies are stubs (no Groth16 verification yet — that
//! requires the verification key from M5 milestone). See
//! `../../../spec/verifier.md`.

use anchor_lang::prelude::*;

declare_id!("EMDfWFhRSZT749WBBARG3K5h1PQUUCCQcgoYtUg658Yv");
// Placeholder devnet keypair generated at scaffold time. Regenerate via
// `solana-keygen new -o target/deploy/zktempo_verifier-keypair.json` and
// `anchor keys sync` once the real deployment keypair is committed (or
// kept in a secrets manager — never in git).

#[program]
pub mod zktempo_verifier {
    use super::*;

    /// One-shot initialization. Bootstraps the light client state PDA with
    /// the genesis validator set hash and starting finalized root.
    ///
    /// Authority: permissioned to the bootstrap caller (one-time only —
    /// subsequent updates are permissionless).
    pub fn bootstrap(
        _ctx: Context<Bootstrap>,
        _genesis_validator_set_hash: [u8; 32],
        _genesis_slot: u64,
        _genesis_state_root: [u8; 32],
    ) -> Result<()> {
        // Stub: initializes the LightClientState PDA with the genesis
        // params. Real implementation lands at M5.
        unimplemented!("see spec/verifier.md")
    }

    /// Verify a Groth16 proof + public inputs, advance the finalized state
    /// if valid.
    ///
    /// Authority: permissionless — the proof is the authority. Anyone can
    /// pay the fee and submit; the verifier accepts the update iff the
    /// proof verifies and the slot is strictly monotonic.
    pub fn update_light_client(
        _ctx: Context<UpdateLightClient>,
        _proof: Vec<u8>,
        _new_slot: u64,
        _new_state_root: [u8; 32],
        _validator_set_hash: [u8; 32],
    ) -> Result<()> {
        // Stub: real implementation will:
        //   1. Reconstruct public inputs from the args.
        //   2. Invoke `sol_alt_bn128_pairing` 3x for Groth16 verification.
        //   3. Check `new_slot > light_client_state.latest_slot`.
        //   4. Check `validator_set_hash` matches active set (or apply a
        //      rotation per spec/light-client.md rules).
        //   5. Persist `(new_slot, new_state_root, last_update_unix_ts)`.
        unimplemented!("see spec/verifier.md")
    }
}

/// Persistent light-client state PDA.
///
/// Seeds: `[b"light_client_state"]`. One per zkTempo verifier deployment.
#[account]
pub struct LightClientState {
    /// Most recently finalized Tempo slot.
    pub latest_slot: u64,
    /// State root finalized at `latest_slot`.
    pub state_root: [u8; 32],
    /// Hash commitment of the active validator set.
    pub validator_set_hash: [u8; 32],
    /// Solana `Clock::unix_timestamp` at the last update. Used by
    /// downstream consumers to detect stale roots.
    pub last_update_unix_ts: i64,
    /// PDA bump seed.
    pub bump: u8,
}

impl LightClientState {
    pub const SEED: &'static [u8] = b"light_client_state";
    /// Size in bytes, **excluding** the 8-byte Anchor discriminator.
    /// u64 (8) + [u8;32] (32) + [u8;32] (32) + i64 (8) + u8 (1) = 81.
    pub const SIZE: usize = 8 + 32 + 32 + 8 + 1;
}

#[derive(Accounts)]
pub struct Bootstrap<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + LightClientState::SIZE,
        seeds = [LightClientState::SEED],
        bump,
    )]
    pub light_client_state: Account<'info, LightClientState>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateLightClient<'info> {
    #[account(
        mut,
        seeds = [LightClientState::SEED],
        bump = light_client_state.bump,
    )]
    pub light_client_state: Account<'info, LightClientState>,
    /// The fee-payer for the update transaction. Not an authority — the
    /// proof is the authority.
    pub submitter: Signer<'info>,
}

#[error_code]
pub enum ZkTempoError {
    #[msg("Groth16 proof verification failed")]
    InvalidProof,
    #[msg("New slot must be strictly greater than the latest finalized slot")]
    NonMonotonicSlot,
    #[msg("Validator set hash does not match the active set")]
    StaleValidatorSet,
    #[msg("Public inputs do not match proof commitments")]
    PublicInputMismatch,
}
